import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Featured from "../components/Featured";
import RiceList from "../components/RiceList";
import styles from "../styles/Home.module.css";

export default function Home({ riceList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ruth RiceShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <RiceList riceList={riceList} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      riceList: res.data,
    },
  };
};
